<a href="https://colab.research.google.com/github/MadhunishaBala/Machine-Learning/blob/main/2337032_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [64]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing

IMPORTION OF THE DATASET

In [65]:
Train_data = pd.read_csv("Adult data.csv")
#Test_data = pd.read_csv("Adult.test.csv")

In [66]:
Train_data.head()

Age          Workclass  Fnlwgt   Education  Education-num  \
0   39          State-gov   77516   Bachelors             13   
1   50   Self-emp-not-inc   83311   Bachelors             13   
2   38            Private  215646     HS-grad              9   
3   53            Private  234721        11th              7   
4   28            Private  338409   Bachelors             13   

        Marital-status          Occupation    Relationship    Race      Sex  \
0        Never-married        Adm-clerical   Not-in-family   White     Male   
1   Married-civ-spouse     Exec-managerial         Husband   White     Male   
2             Divorced   Handlers-cleaners   Not-in-family   White     Male   
3   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
4   Married-civ-spouse      Prof-specialty            Wife   Black   Female   

   Capital-gain  Capital-loss  Hours-per-week  Native-country  Income  
0          2174             0              40   United-States   <=50K  
1             0             0              13   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40   United-States   <=50K  
4             0             0              40            Cuba   <=50K

In [67]:
Train_data.shape

(32561, 15)

In [68]:
Train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Age             32561 non-null  int64 
 1   Workclass       32561 non-null  object
 2   Fnlwgt          32561 non-null  int64 
 3   Education       32561 non-null  object
 4   Education-num   32561 non-null  int64 
 5   Marital-status  32561 non-null  object
 6   Occupation      32561 non-null  object
 7   Relationship    32561 non-null  object
 8   Race            32561 non-null  object
 9   Sex             32561 non-null  object
 10  Capital-gain    32561 non-null  int64 
 11  Capital-loss    32561 non-null  int64 
 12  Hours-per-week  32561 non-null  int64 
 13  Native-country  32561 non-null  object
 14  Income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB


In [69]:
Train_data.describe()

Age        Fnlwgt  Education-num  Capital-gain  Capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000   
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830   
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       Hours-per-week  
count    32561.000000  
mean        40.437456  
std         12.347429  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

Replacing the "?" will NaN

In [70]:
Train_data.replace('?', np.NaN, inplace=True)
#Test_data.replace('?', np.NaN, inplace=True)

In [71]:
print("Train_data Missing Values:")
print(Train_data.isnull().sum())

#print("\nTest_data Missing Values:")
#rint(Test_data.isnull().sum())

Train_data Missing Values:
Age               0
Workclass         0
Fnlwgt            0
Education         0
Education-num     0
Marital-status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital-gain      0
Capital-loss      0
Hours-per-week    0
Native-country    0
Income            0
dtype: int64


Filling the null values with the mode

In [72]:
Train_data.fillna(Train_data.mode().iloc[0], inplace=True)
#Test_data.fillna(Test_data.mode().iloc[0], inplace=True)

In [73]:
print("Train_data Missing Values:")
print(Train_data.isnull().sum())

print("\nTest_data Missing Values:")
#print(Test_data.isnull().sum())

Train_data Missing Values:
Age               0
Workclass         0
Fnlwgt            0
Education         0
Education-num     0
Marital-status    0
Occupation        0
Relationship      0
Race              0
Sex               0
Capital-gain      0
Capital-loss      0
Hours-per-week    0
Native-country    0
Income            0
dtype: int64

Test_data Missing Values:


## Dropping the columns not related to income

In [74]:
Train_data.drop(['Fnlwgt'],axis=1,inplace=True)

In [75]:
Train_data.head()

Age          Workclass   Education  Education-num       Marital-status  \
0   39          State-gov   Bachelors             13        Never-married   
1   50   Self-emp-not-inc   Bachelors             13   Married-civ-spouse   
2   38            Private     HS-grad              9             Divorced   
3   53            Private        11th              7   Married-civ-spouse   
4   28            Private   Bachelors             13   Married-civ-spouse   

           Occupation    Relationship    Race      Sex  Capital-gain  \
0        Adm-clerical   Not-in-family   White     Male          2174   
1     Exec-managerial         Husband   White     Male             0   
2   Handlers-cleaners   Not-in-family   White     Male             0   
3   Handlers-cleaners         Husband   Black     Male             0   
4      Prof-specialty            Wife   Black   Female             0   

   Capital-loss  Hours-per-week  Native-country  Income  
0             0              40   United-States   <=50K  
1             0              13   United-States   <=50K  
2             0              40   United-States   <=50K  
3             0              40   United-States   <=50K  
4             0              40            Cuba   <=50K

In [76]:
#Test_data.drop(['Fnlwgt'],axis=1,inplace=True)

##Visualizing the types of data

In [77]:
print("Income Count:")
print(Train_data['Income'].value_counts()) #Binary
print("\nWorkclass")
print(Train_data['Workclass'].value_counts()) #8
print("\nEducation")
print(Train_data['Education'].value_counts()) #16
print("\nMarital-status")
print(Train_data['Marital-status'].value_counts()) #7
print("\nOccupation")
print(Train_data['Occupation'].value_counts()) #14
print("\nRelationship")
print(Train_data['Relationship'].value_counts()) #6
print("\nRace")
print(Train_data['Race'].value_counts()) #5
print("\nSex")
print(Train_data['Sex'].value_counts()) #Binary
print("\nNative-country")
print(Train_data['Native-country'].value_counts()) #41


Income Count:
 <=50K    24720
 >50K      7841
Name: Income, dtype: int64

Workclass
 Private             22696
 Self-emp-not-inc     2541
 Local-gov            2093
 ?                    1836
 State-gov            1298
 Self-emp-inc         1116
 Federal-gov           960
 Without-pay            14
 Never-worked            7
Name: Workclass, dtype: int64

Education
 HS-grad         10501
 Some-college     7291
 Bachelors        5355
 Masters          1723
 Assoc-voc        1382
 11th             1175
 Assoc-acdm       1067
 10th              933
 7th-8th           646
 Prof-school       576
 9th               514
 12th              433
 Doctorate         413
 5th-6th           333
 1st-4th           168
 Preschool          51
Name: Education, dtype: int64

Marital-status
 Married-civ-spouse       14976
 Never-married            10683
 Divorced                  4443
 Separated                 1025
 Widowed                    993
 Married-spouse-absent      418
 Married-AF-spouse        

## BINARY ENCODING

In [78]:
Train_data['Income']=Train_data['Income'].apply(lambda x:0 if x == '>=50k' else 1)
Train_data['Income'].head()
# >=50k --> 0
# <=50k -->1

0    1
1    1
2    1
3    1
4    1
Name: Income, dtype: int64

In [79]:
#Test_data['Income']=Test_data['Income'].apply(lambda x:0 if x == '>=50k' else 1)
#Test_data['Income'].head()

In [80]:
Train_data['Sex']=Train_data['Sex'].apply(lambda x:0 if x == 'Male' else 1)
Train_data['Sex'].head()
#Male =1 Female =0

0    1
1    1
2    1
3    1
4    1
Name: Sex, dtype: int64

In [81]:
#Test_data['Sex']=Test_data['Sex'].apply(lambda x:0 if x == '>=50k' else 1)
#Test_data['Sex'].head()

## Label Encoding

In [82]:
label_encoder = preprocessing.LabelEncoder()
Train_data['Workclass']= label_encoder.fit_transform(Train_data['Workclass'])
Train_data['Workclass'].unique()

#Test_data['Workclass']= label_encoder.fit_transform(Test_data['Workclass'])
#Test_data['Workclass'].unique()

array([7, 6, 4, 1, 2, 0, 5, 8, 3])

In [83]:
Train_data['Education']= label_encoder.fit_transform(Train_data['Education'])
Train_data['Education'].unique()

#Test_data['Education']= label_encoder.fit_transform(Test_data['Education'])
#Test_data['Education'].unique()


array([ 9, 11,  1, 12,  6, 15,  7,  8,  5, 10, 14,  4,  0,  3, 13,  2])

In [84]:
Train_data['Marital-status']= label_encoder.fit_transform(Train_data['Marital-status'])
Train_data['Marital-status'].unique()

#Test_data['Marital-status']= label_encoder.fit_transform(Test_data['Marital-status'])
#Test_data['Marital-status'].unique()

array([4, 2, 0, 3, 5, 1, 6])

In [85]:
Train_data['Occupation']= label_encoder.fit_transform(Train_data['Occupation'])
Train_data['Occupation'].unique()

#Test_data['Occupation']= label_encoder.fit_transform(Test_data['Occupation'])
#Test_data['Occupation'].unique()

array([ 1,  4,  6, 10,  8, 12,  3, 14,  5,  7, 13,  0, 11,  2,  9])

In [86]:
Train_data['Relationship']= label_encoder.fit_transform(Train_data['Relationship'])
Train_data['Relationship'].unique()

#Test_data['Relationship']= label_encoder.fit_transform(Test_data['Relationship'])
#Test_data['Relationship'].unique()

array([1, 0, 5, 3, 4, 2])

In [87]:
Train_data['Race']= label_encoder.fit_transform(Train_data['Race'])
Train_data['Race'].unique()

#Test_data['Race']= label_encoder.fit_transform(Test_data['Race'])
#Test_data['Race'].unique()

array([4, 2, 1, 0, 3])

In [88]:
Train_data['Native-country']= label_encoder.fit_transform(Train_data['Native-country'])
Train_data['Native-country'].unique()

#Test_data['Native-country']= label_encoder.fit_transform(Test_data['Native-country'])
#Test_data['Native-country'].unique()

array([39,  5, 23, 19,  0, 26, 35, 33, 16,  9,  2, 11, 20, 30, 22, 31,  4,
        1, 37,  7, 25, 36, 14, 32,  6,  8, 10, 13,  3, 24, 41, 29, 28, 34,
       38, 12, 27, 40, 17, 21, 18, 15])

In [89]:
Train_data.head()

Age  Workclass  Education  Education-num  Marital-status  Occupation  \
0   39          7          9             13               4           1   
1   50          6          9             13               2           4   
2   38          4         11              9               0           6   
3   53          4          1              7               2           6   
4   28          4          9             13               2          10   

   Relationship  Race  Sex  Capital-gain  Capital-loss  Hours-per-week  \
0             1     4    1          2174             0              40   
1             0     4    1             0             0              13   
2             1     4    1             0             0              40   
3             0     2    1             0             0              40   
4             5     2    1             0             0              40   

   Native-country  Income  
0              39       1  
1              39       1  
2              39       1  
3              39       1  
4               5       1

In [90]:
#Test_data.head()

In [94]:
X= Train_data.drop(['Income'], axis=1)
y = Train_data['Income']
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=40)
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier()

model1 = rfc.fit(X_train, y_train)
prediction1 = model1.predict(X_test)

print("Acc on training data: {:,.3f}".format(rfc.score(X_train, y_train)))
print("Acc on test data: {:,.3f}".format(rfc.score(X_test, y_test)))

Acc on training data: 1.000
Acc on test data: 1.000


## NAIVE BAYES

In [92]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report
X_train = Train_data.drop('Income', axis=1)
y_train = Train_data['Income']
X_test = Test_data.drop('Income', axis=1)
y_test = Test_data['Income']

naive_bayes_model = GaussianNB()

naive_bayes_model.fit(X_train, y_train)

y_pred_nb = naive_bayes_model.predict(X_test)

print("Naive Bayes Accuracy:", accuracy_score(y_test, y_pred_nb))
print("Naive Bayes Classification Report:")
print(classification_report(y_test, y_pred_nb))

Naive Bayes Accuracy: 1.0
Naive Bayes Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     16281

    accuracy                           1.00     16281
   macro avg       1.00      1.00      1.00     16281
weighted avg       1.00      1.00      1.00     16281



## RANDOM FOREST

In [93]:
from sklearn.ensemble import RandomForestClassifier

random_forest_model = RandomForestClassifier(n_estimators=100, random_state=42)

random_forest_model.fit(X_train, y_train)


y_pred_rf = random_forest_model.predict(X_test)


print("Random Forest Accuracy:", accuracy_score(y_test, y_pred_rf))
print("Random Forest Classification Report:")
print(classification_report(y_test, y_pred_rf))


Random Forest Accuracy: 1.0
Random Forest Classification Report:
              precision    recall  f1-score   support

           1       1.00      1.00      1.00     16281

    accuracy                           1.00     16281
   macro avg       1.00      1.00      1.00     16281
weighted avg       1.00      1.00      1.00     16281



## TEST SPLIT FROM TRAIN

In [95]:
from sklearn.model_selection import cross_val_score

nb_model = GaussianNB()
cv_scores_nb = cross_val_score(nb_model, X, y, cv=5, scoring='accuracy')
print(f"Cross-Validation Scores for Naïve Bayes: {cv_scores_nb}")

rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
cv_scores_rf = cross_val_score(rf_model, X, y, cv=5, scoring='accuracy')
print(f"Cross-Validation Scores for Random Forest: {cv_scores_rf}")


Cross-Validation Scores for Naïve Bayes: [1. 1. 1. 1. 1.]
Cross-Validation Scores for Random Forest: [1. 1. 1. 1. 1.]


In [96]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
print(confusion_matrix(y_test, prediction1))

[[9769]]


In [97]:
print(classification_report(y_test, prediction1))

              precision    recall  f1-score   support

           1       1.00      1.00      1.00      9769

    accuracy                           1.00      9769
   macro avg       1.00      1.00      1.00      9769
weighted avg       1.00      1.00      1.00      9769

